spring:
  application:
    name: Product
  datasource:
    url: jdbc:mysql://localhost:3306/newDB
    username: root
    password: 4281
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8086
logging:
  level:
    root: warn