server:
  port: 8081

spring:
  application:
    name: Gateway
  main:
    allow-circular-references: true
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: Identity
          uri: lb://Identity
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter
        - id: Product
          uri: lb://Product
          predicates:
            - Path=/api/v1/product/**
          filters:
            - AuthenticationFilter
        - id: Wishlist
          uri: lb://Wishlist
          predicates:
            - Path=/api/v1/wishlist/**
          filters:
            - AuthenticationFilter
        - id: Orders
          uri: lb://Orders
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthenticationFilter
        - id: Cart
          uri: lb://Cart
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - AuthenticationFilter
        - id: Discount
          uri: lb://Discount
          predicates:
            - Path=/api/v1/discount/**
          filters:
            - AuthenticationFilter
            
            
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: warn